version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r backend/requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest backend/tests

workflows:
  build:
    jobs:
      - build-and-test
