version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10

jobs:
  build-and-test:
    executor: python-executor
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            cd backend
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest

      - run:
          name: Run tests with pytest
          command: |
            cd backend
            # Set WEAVIATE_URL to a dummy value to prevent import error
            export WEAVIATE_URL="http://dummy-url:8080"
            PYTHONPATH=./app venv/bin/pytest app/tests/

workflows:
  build:
    jobs:
      - build-and-test
