version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10  # CircleCI Python Docker image
    working_directory: ~/repo/backend
    steps:
      - checkout
      - run:
          name: Set up Python environment
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests with dummy Weaviate environment
          command: |
            export WEAVIATE_URL="http://dummy-url:8080"
            export WEAVIATE_API_KEY="dummy-api-key"
            PYTHONPATH=./app venv/bin/pytest app/tests/

workflows:
  test:
    jobs:
      - test
